/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author 57312
 */
public class READ extends javax.swing.JInternalFrame {

    /**
     * Creates new form READ
     */
    
    public READ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_lecciones = new javax.swing.JTable();
        sdfg2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        correcta1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        JB_aceptarRead = new javax.swing.JButton();
        lecc2 = new javax.swing.JLabel();
        correcta2 = new javax.swing.JRadioButton();
        gfds2 = new javax.swing.JRadioButton();
        dsds2 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel1.setText("READ");

        T_lecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"leccion 1"},
                {"leccion 2"},
                {"leccion 3"},
                {"leccion 4"},
                {"leccion 5"},
                {"leccion 6"},
                {"leccion 7"},
                {"leccion 8"},
                {"leccion 9"},
                {null}
            },
            new String [] {
                "lecciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        T_lecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_leccionesMouseClicked(evt);
            }
        });
        T_lecciones.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                T_leccionesComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(T_lecciones);

        sdfg2.setText("cual de estos es TE en ingles");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("PLEASE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(correcta1);
        correcta1.setText(" TEA");
        correcta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correcta1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("HELLO");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        JB_aceptarRead.setText("aceptar");
        JB_aceptarRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_aceptarReadActionPerformed(evt);
            }
        });

        lecc2.setText("cuel de estos es casa en ingles");

        buttonGroup2.add(correcta2);
        correcta2.setText("home");
        correcta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correcta2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(gfds2);
        gfds2.setText("tree");
        gfds2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gfds2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(dsds2);
        dsds2.setText("tea");
        dsds2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsds2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JB_aceptarRead)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gfds2)
                                    .addComponent(correcta2)
                                    .addComponent(dsds2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton1)
                                    .addComponent(correcta1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(sdfg2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lecc2)))
                        .addContainerGap(104, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lecc2)
                                    .addComponent(sdfg2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(correcta2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(correcta1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(gfds2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dsds2))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_aceptarRead)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void JB_aceptarReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_aceptarReadActionPerformed
        // TODO add your handling code here:
           
    sdfg2.setVisible(!sdfg2.isVisible());
    jRadioButton1.setVisible(!jRadioButton1.isVisible());
    correcta1.setVisible(!correcta1.isVisible());
    jRadioButton3.setVisible(!jRadioButton3.isVisible());
    
    
    }//GEN-LAST:event_JB_aceptarReadActionPerformed

    private void correcta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correcta1ActionPerformed
        // TODO add your handling code here:
        sdfg2.setVisible(false);
    jRadioButton1.setVisible(false);
    correcta1.setVisible(false);
    jRadioButton3.setVisible(false);
    sdfg2.setVisible(false);
    }//GEN-LAST:event_correcta1ActionPerformed

    private void correcta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correcta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correcta2ActionPerformed

    private void dsds2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsds2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsds2ActionPerformed

    private void gfds2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gfds2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gfds2ActionPerformed

    private void T_leccionesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_T_leccionesComponentHidden
       
    }//GEN-LAST:event_T_leccionesComponentHidden

    private void T_leccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_leccionesMouseClicked
        // TODO add your handling code here:
        sdfg2.setVisible(false);
    correcta2.setVisible(false);
    gfds2.setVisible(false);
    dsds2.setVisible(false);
    }//GEN-LAST:event_T_leccionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_aceptarRead;
    public javax.swing.JTable T_lecciones;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JRadioButton correcta1;
    public javax.swing.JRadioButton correcta2;
    public javax.swing.JRadioButton dsds2;
    public javax.swing.JRadioButton gfds2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lecc2;
    public javax.swing.JLabel sdfg2;
    // End of variables declaration//GEN-END:variables
}
