
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author 57312
 */
public class clase2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form clase2
     */
    public clase2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejecutivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        especial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        corriente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        imagenLabel = new javax.swing.JLabel();

        ejecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutivoActionPerformed(evt);
            }
        });

        jLabel2.setText("ejecutivo");

        jLabel3.setText("especial");

        jLabel1.setText("corriente");

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"corriente", "15000"},
                {"ejecutivo", "20000"},
                {"especial", "30000"},
                {null, null},
                {null, null}
            },
            new String [] {
                "monbre del plat", "valor del plato"
            }
        ));
        tablita.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablitaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablita);

        jLabel4.setText(" seleccione el plato y escriba la cantidad de platos que desea comprar.");

        aceptar.setText("aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corriente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(aceptar)))
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(corriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aceptar))
                    .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablitaMouseClicked
       
        
        
    }//GEN-LAST:event_tablitaMouseClicked

    private void tablitaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablitaAncestorAdded
        
        
    }//GEN-LAST:event_tablitaAncestorAdded

    private void ejecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecutivoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        
     String textoCorriente = corriente.getText();
    int cantidadCorriente = Integer.parseInt(textoCorriente);

    // Obtener el modelo de datos de tabla2
    DefaultTableModel model = (DefaultTableModel) clase3.tabla2.getModel();

    int seleccionar = tablita.getSelectedRow();
    String[] RegistroDatos = new String[5]; // Supongo que hay 3 columnas en tabla2
    RegistroDatos[0] = tablita.getValueAt(seleccionar, 0).toString();
    RegistroDatos[1] = tablita.getValueAt(seleccionar, 1).toString();
    RegistroDatos[2] = String.valueOf(cantidadCorriente); // Agregar la cantidad
    
    // Calcular el subtotal multiplicando el valor del plato por la cantidad
    int valorPlato = Integer.parseInt(tablita.getValueAt(seleccionar, 1).toString());
    int subtotal = valorPlato * cantidadCorriente;
    RegistroDatos[3] = String.valueOf(subtotal); 
    
    model.addRow(RegistroDatos);
    clase3.tabla2.setModel(model);
    
    // Verificar la opción seleccionada en la tabla
        String nombrePlato = tablita.getValueAt(seleccionar, 0).toString();
        if (nombrePlato.equals("corriente")) {
            // Muestra la imagen "corriente.jpg"
            ImageIcon icono = new ImageIcon("corriente.jpg");
            imagenLabel.setIcon(icono);
        } else if (nombrePlato.equals("ejecutivo")) {
            // Muestra la imagen "ejecutivo.jpg"
            ImageIcon icono = new ImageIcon("ejecutivo.jpg");
            imagenLabel.setIcon(icono);
        } else {
            ImageIcon icono = new ImageIcon("especial.jpg");
            
            imagenLabel.setIcon(icono);
        }
    
    
    }//GEN-LAST:event_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField corriente;
    private javax.swing.JTextField ejecutivo;
    private javax.swing.JTextField especial;
    public javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables
}
