
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author 57312
 */
public class clase3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form clase3
     */
    public clase3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        valor_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pagar_con_iva = new javax.swing.JTextField();
        JT_comprar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        descuentos = new javax.swing.JTextField();

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre del plato", "valor del plato", "cantidad", "Subtotal"
            }
        ));
        tabla2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabla2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabla2);

        valor_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_totalActionPerformed(evt);
            }
        });

        jLabel1.setText("total");

        jLabel2.setText("total con iva o propina ");

        pagar_con_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_con_ivaActionPerformed(evt);
            }
        });

        JT_comprar.setText("finalizar compra");
        JT_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_comprarActionPerformed(evt);
            }
        });

        jLabel3.setText("descuentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(descuentos, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valor_total, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(JT_comprar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagar_con_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JT_comprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(descuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valor_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pagar_con_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabla2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla2AncestorAdded

    private void valor_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_totalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_valor_totalActionPerformed

    private void pagar_con_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_con_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagar_con_ivaActionPerformed

    private void JT_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_comprarActionPerformed
        // Obtener el modelo de datos de la tabla2
        DefaultTableModel model = (DefaultTableModel) tabla2.getModel();

        int total = 0; // Inicializamos el total a cero

        // Recorremos todas las filas de la tabla2 y sumamos los subtotales
        for (int i = 0; i < model.getRowCount(); i++) {
            int subtotal = Integer.parseInt(model.getValueAt(i, 3).toString()); // Suponemos que el subtotal está en la columna 3
            total += subtotal;
        }

        
        // Mostramos el total en el JTextField valor_total
        valor_total.setText(String.valueOf(total));

        if (total > 125000) {
            double iva = total * 0.19;
            double totalConIva = total + iva;
            pagar_con_iva.setText(String.valueOf(totalConIva));
        }
        
        
    double subtotal=0;
        double descuento=0;
        double total2=0;
    // Recorremos todas las filas de la tabla2 y sumamos los subtotales con descuento
    for (int i = 0; i < model.getRowCount(); i++) {
           
        // Suponemos que la cantidad está en la columna 2
        int cantidad = Integer.parseInt(model.getValueAt(i, 2).toString());
        if(cantidad==1){
            double valorPlato = Double.parseDouble(model.getValueAt(i, 1).toString());
            subtotal = subtotal+valorPlato;
                      
        }
    }
    descuento = subtotal * 0.05;
    total2=subtotal-descuento;  
    // Mostramos el descuento en el JT descuentos
    descuentos.setText(String.valueOf(descuento));
    valor_total.setText(String.valueOf(total2));
    
    if (total2 > 125000) {
            double iva2 = total2 * 0.19;
            double totalConIva2 = total2 + iva2;
            pagar_con_iva.setText(String.valueOf(totalConIva2));
        }
    
    }//GEN-LAST:event_JT_comprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JT_comprar;
    public javax.swing.JTextField descuentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField pagar_con_iva;
    public static javax.swing.JTable tabla2;
    public javax.swing.JTextField valor_total;
    // End of variables declaration//GEN-END:variables
}
